/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pruebas.sheetsmaven;

import com.google.api.services.sheets.v4.Sheets;
import com.google.api.services.sheets.v4.model.ValueRange;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ELVIS
 */
public class Busqueda extends javax.swing.JFrame {
    
    private static Sheets sheetServicio;
    private static String Nombre_Aplicacion="Ejemplo google sheets";
    private static String Google_Sheet_Id="125WxoxoodpoW4W06gagqt_X1iy_q4_Ey0MU7-nuaJy4";//1pOxvp2Gf8-JP4QulwtZpMo8uuT7XJdzyG7bUqNeiqUA
    private static String hojaID="hoja 3";
    private static String Rango=hojaID+"!A2:CO";//base final!A2:CO

    /**
     * Creates new form Busqueda
     */
    public Busqueda() {
        initComponents();
        pbBusqueda.setVisible(false);
        pbBusqueda.setBackground(Color.red);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDistrito = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMac = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtOt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCtoNap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPiso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPartener = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        txtHorallegada = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTicket = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtHorafinalizada = new javax.swing.JTextField();
        pbBusqueda = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLogObservacion = new javax.swing.JTextArea();
        txtMotivoCreacion = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtTipoSolucion = new javax.swing.JTextField();
        txtRegistroLLegada = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnTrabajo = new javax.swing.JButton();
        btnPartener = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        btnLlegada = new javax.swing.JButton();
        btnRegistrollegada = new javax.swing.JButton();
        btnSolucion = new javax.swing.JButton();
        btnMotivoCreacion = new javax.swing.JButton();
        btnFinalizada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setText("DNI");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        txtNombre.setEditable(false);

        jLabel3.setText("Provincia");

        txtProvincia.setEditable(false);

        jLabel4.setText("Direccion");

        txtDireccion.setEditable(false);

        jLabel5.setText("Distrito");

        txtDistrito.setEditable(false);

        jLabel6.setText("MAC");

        txtMac.setEditable(false);

        jLabel7.setText("CP");

        txtCp.setEditable(false);

        jLabel8.setText("OT");

        txtOt.setEditable(false);

        jLabel9.setText("Telefono");

        txtTelefono.setEditable(false);

        txtPuerto.setEditable(false);

        jLabel10.setText("CTO/NAP");

        txtCtoNap.setEditable(false);

        jLabel11.setText("Piso");

        txtPiso.setEditable(false);

        jLabel12.setText("Puerto");

        jLabel15.setText("Partener");

        txtPartener.setEditable(false);

        jLabel16.setText("Tipo trabajo");

        txtTipo.setEditable(false);

        jLabel17.setText("Ticket");

        txtTicket.setEditable(false);

        jLabel19.setText("Hora de llegada");

        pbBusqueda.setBackground(new java.awt.Color(204, 204, 204));
        pbBusqueda.setForeground(new java.awt.Color(0, 51, 255));
        pbBusqueda.setIndeterminate(true);

        txtLogObservacion.setColumns(20);
        txtLogObservacion.setRows(5);
        jScrollPane1.setViewportView(txtLogObservacion);

        txtMotivoCreacion.setEditable(false);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel20.setText("Estado");

        txtEstado.setEditable(false);

        txtTipoSolucion.setEditable(false);

        jLabel21.setText("Registro llegada");

        btnTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono_guardar.png"))); // NOI18N
        btnTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajoActionPerformed(evt);
            }
        });

        btnPartener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono_guardar.png"))); // NOI18N
        btnPartener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartenerActionPerformed(evt);
            }
        });

        btnEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono_guardar.png"))); // NOI18N
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        btnTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono_guardar.png"))); // NOI18N
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });

        btnLlegada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono_guardar.png"))); // NOI18N
        btnLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlegadaActionPerformed(evt);
            }
        });

        btnRegistrollegada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono_guardar.png"))); // NOI18N
        btnRegistrollegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrollegadaActionPerformed(evt);
            }
        });

        btnSolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono_guardar.png"))); // NOI18N
        btnSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolucionActionPerformed(evt);
            }
        });

        btnMotivoCreacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono_guardar.png"))); // NOI18N
        btnMotivoCreacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotivoCreacionActionPerformed(evt);
            }
        });

        btnFinalizada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono_guardar.png"))); // NOI18N
        btnFinalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(45, 45, 45)
                                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(btnBuscar)))
                                .addGap(39, 39, 39)
                                .addComponent(btnActualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCp, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCtoNap, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtOt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPartener, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel21))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtHorallegada, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                                    .addComponent(txtRegistroLLegada))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtMotivoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtHorafinalizada, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnFinalizada, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnMotivoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(btnTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPartener, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRegistrollegada, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtTipoSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMac, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnBuscar)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(txtPartener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnPartener, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipoSolucion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(txtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(txtHorallegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMotivoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMotivoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtHorafinalizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFinalizada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtOt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrollegada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtRegistroLLegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCtoNap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        pbBusqueda.setVisible(true);
        if (txtBusqueda.getText().isEmpty()) {
          pbBusqueda.setVisible(false);
          txtLogObservacion.setText("Ingrese un DNI");
           
        }else{
            HiloBuscarDatos hiloBuscarDatos=new HiloBuscarDatos();
            Thread hilo=new Thread(hiloBuscarDatos);
            hilo.start();
        }
       
       
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        pbBusqueda.setVisible(true);
        if (txtBusqueda.getText().isEmpty()) {
            pbBusqueda.setVisible(false);
            txtLogObservacion.setText("Ingrese un DNI");

        }else{

            HiloActualizarDatos hiloActualizarDatos=new HiloActualizarDatos();
            Thread hilo=new Thread(hiloActualizarDatos);
            hilo.start();
        }
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnMotivoCreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotivoCreacionActionPerformed
        // TODO add your handling code here:
        pbBusqueda.setVisible(true);
        if (txtBusqueda.getText().isEmpty()) {
            pbBusqueda.setVisible(false);
            txtLogObservacion.setText("Ingrese un DNI");

        }else{
            HiloActualizarDatosPorCelda hiliActualizarDatosPorCelda=new HiloActualizarDatosPorCelda("AH", txtMotivoCreacion.getText());
            Thread hilo=new Thread(hiliActualizarDatosPorCelda);
            hilo.start();
        }
        
    }//GEN-LAST:event_btnMotivoCreacionActionPerformed

    private void btnFinalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizadaActionPerformed
        // TODO add your handling code here:
        pbBusqueda.setVisible(true);
        if (txtBusqueda.getText().isEmpty()) {
            pbBusqueda.setVisible(false);
            txtLogObservacion.setText("Ingrese un DNI");

        }else{
            HiloActualizarDatosPorCelda hiliActualizarDatosPorCelda=new HiloActualizarDatosPorCelda("BY", txtHorafinalizada.getText());
            Thread hilo=new Thread(hiliActualizarDatosPorCelda);
            hilo.start();
        }
        
    }//GEN-LAST:event_btnFinalizadaActionPerformed

    private void btnLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlegadaActionPerformed
        // TODO add your handling code here:
        pbBusqueda.setVisible(true);
        if (txtBusqueda.getText().isEmpty()) {
            pbBusqueda.setVisible(false);
            txtLogObservacion.setText("Ingrese un DNI");

        }else{
            HiloActualizarDatosPorCelda hiliActualizarDatosPorCelda=new HiloActualizarDatosPorCelda("BX", txtHorallegada.getText());
            Thread hilo=new Thread(hiliActualizarDatosPorCelda);
            hilo.start();
        }
        
        
    }//GEN-LAST:event_btnLlegadaActionPerformed

    private void btnRegistrollegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrollegadaActionPerformed
        // TODO add your handling code here:
        pbBusqueda.setVisible(true);
        if (txtBusqueda.getText().isEmpty()) {
            pbBusqueda.setVisible(false);
            txtLogObservacion.setText("Ingrese un DNI");

        }else{
            HiloActualizarDatosPorCelda hiliActualizarDatosPorCelda=new HiloActualizarDatosPorCelda("BZ", txtRegistroLLegada.getText());
            Thread hilo=new Thread(hiliActualizarDatosPorCelda);
            hilo.start();
        }
        
    }//GEN-LAST:event_btnRegistrollegadaActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        // TODO add your handling code here:
        pbBusqueda.setVisible(true);
        if (txtBusqueda.getText().isEmpty()) {
            pbBusqueda.setVisible(false);
            txtLogObservacion.setText("Ingrese un DNI");

        }else{
            HiloActualizarDatosPorCelda hiliActualizarDatosPorCelda=new HiloActualizarDatosPorCelda("C", txtTicket.getText());
            Thread hilo=new Thread(hiliActualizarDatosPorCelda);
            hilo.start();
        }
        
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolucionActionPerformed
        // TODO add your handling code here:
        pbBusqueda.setVisible(true);
        if (txtBusqueda.getText().isEmpty()) {
            pbBusqueda.setVisible(false);
            txtLogObservacion.setText("Ingrese un DNI");

        }else{
            HiloActualizarDatosPorCelda hiliActualizarDatosPorCelda=new HiloActualizarDatosPorCelda("BT", txtTipoSolucion.getText());
            Thread hilo=new Thread(hiliActualizarDatosPorCelda);
            hilo.start();
        }
        
    }//GEN-LAST:event_btnSolucionActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        // TODO add your handling code here:
        pbBusqueda.setVisible(true);
        if (txtBusqueda.getText().isEmpty()) {
            pbBusqueda.setVisible(false);
            txtLogObservacion.setText("Ingrese un DNI");

        }else{
            HiloActualizarDatosPorCelda hiliActualizarDatosPorCelda=new HiloActualizarDatosPorCelda("BQ", txtEstado.getText());
            Thread hilo=new Thread(hiliActualizarDatosPorCelda);
            hilo.start();
        }
        
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void btnPartenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartenerActionPerformed
        // TODO add your handling code here:
        pbBusqueda.setVisible(true);
        if (txtBusqueda.getText().isEmpty()) {
            pbBusqueda.setVisible(false);
            txtLogObservacion.setText("Ingrese un DNI");

        }else{
            HiloActualizarDatosPorCelda hiliActualizarDatosPorCelda=new HiloActualizarDatosPorCelda("BP", txtPartener.getText());
            Thread hilo=new Thread(hiliActualizarDatosPorCelda);
            hilo.start();
        }
    }//GEN-LAST:event_btnPartenerActionPerformed

    private void btnTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajoActionPerformed
        // TODO add your handling code here:
        pbBusqueda.setVisible(true);
        if (txtBusqueda.getText().isEmpty()) {
            pbBusqueda.setVisible(false);
            txtLogObservacion.setText("Ingrese un DNI");

        }else{
            HiloActualizarDatosPorCelda hiliActualizarDatosPorCelda=new HiloActualizarDatosPorCelda("BQ", txtTipo.getText());
            Thread hilo=new Thread(hiliActualizarDatosPorCelda);
            hilo.start();
        }
    }//GEN-LAST:event_btnTrabajoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
        
        
        
        
    }
    public class HiloBuscarDatos implements Runnable{

        @Override
        public void run() {
         try {
            Sheetsc sheetsc=new Sheetsc(Nombre_Aplicacion);
            System.out.println(""+Google_Sheet_Id);
            sheetServicio=sheetsc.obtenerServicioSheets();
        
        
            //Mostrar datos
            ValueRange response=sheetServicio.spreadsheets().values()
                    .get(Google_Sheet_Id, Rango)
                    .execute();
            List<List<Object>> values=response.getValues();
            if (values==null|| values.isEmpty()) {
                pbBusqueda.setVisible(false);
                System.out.println("No hay datos");
            }else{
                //int index=1;
                Boolean valorEncotrado=false;
                for(List fila:values){
                     
                    if(fila.get(5).toString().equals(txtBusqueda.getText())){
                        valorEncotrado=true;
                        pbBusqueda.setVisible(false);
                        txtNombre.setText(fila.get(6).toString());
                        txtProvincia.setText(fila.get(12).toString());
                        txtDistrito.setText(fila.get(11).toString());
                        txtDireccion.setText(fila.get(9).toString());
                        txtTelefono.setText(fila.get(7).toString());
                        txtMac.setText(fila.get(19).toString());
                        txtOt.setText(fila.get(21).toString());
                        txtCtoNap.setText(fila.get(18).toString());
                        txtPuerto.setText(fila.get(23).toString());
                        txtLogObservacion.setText(fila.get(74).toString());
                       //actualizables
                        txtPartener.setText(fila.get(67).toString());
                        txtTicket.setText(fila.get(2).toString());
                        txtTipo.setText(fila.get(1).toString());
                        txtMotivoCreacion.setText(fila.get(33).toString());
                        txtHorallegada.setText(fila.get(75).toString());
                        txtHorafinalizada.setText(fila.get(76).toString());
                        txtEstado.setText(fila.get(70).toString());
                        txtTipoSolucion.setText(fila.get(71).toString());
                        txtRegistroLLegada.setText(fila.get(77).toString());
                      
                      
                    }
                }
                if(!valorEncotrado){
                    pbBusqueda.setVisible(false);
                    txtLogObservacion.setText("El DNI no existe");
                }
                
            }
        } catch (Exception e) {
            pbBusqueda.setVisible(false);
            e.printStackTrace();
            txtLogObservacion.setText(""+e);
           }   
        }
        
    }
    public class HiloActualizarDatos implements Runnable{

        @Override
        public void run() {
         try {
            Sheetsc sheetsc=new Sheetsc(Nombre_Aplicacion);
            System.out.println(""+Google_Sheet_Id);
            sheetServicio=sheetsc.obtenerServicioSheets();
        
        
            ValueRange response=sheetServicio.spreadsheets().values()
                    .get(Google_Sheet_Id, Rango)
                    .execute();
        
            List<List<Object>> values=response.getValues();

            if (values==null|| values.isEmpty()) {
                pbBusqueda.setVisible(false);
                System.out.println("No hay datos");
            }else{
                int index=1;
                Boolean valorEncotrado=false;
                for(List fila:values){
                    index++;
                    if(fila.get(5).toString().equals(txtBusqueda.getText())){
                       valorEncotrado=true;
                      
                        actualizarCelda("BX"+index, txtHorallegada.getText());
                        actualizarCelda("BY"+index, txtHorafinalizada.getText());
                        actualizarCelda("BZ"+index, txtRegistroLLegada.getText()); 
                    }
                    pbBusqueda.setVisible(false);
                    txtLogObservacion.setText("Registro Actualizado");
                    
                   
                }
                if(!valorEncotrado){
                    pbBusqueda.setVisible(false);
                    txtLogObservacion.setText("El DNI no existe, no se pudo actualizar");
                }
           
               
          
            }
        } catch (Exception e) {
            pbBusqueda.setVisible(false);
            e.printStackTrace();
            txtLogObservacion.setText(""+e);
           }   
        }
        
    }
    public class HiloActualizarDatosPorCelda implements Runnable{
        private String celda;
        private String valor;
        public HiloActualizarDatosPorCelda(String celda,String valor){
            this.celda=celda;
            this.valor=valor;
            
        }

        @Override
        public void run() {
             try {
            Sheetsc sheetsc=new Sheetsc(Nombre_Aplicacion);
            System.out.println(""+Google_Sheet_Id);
            sheetServicio=sheetsc.obtenerServicioSheets();
        
        
            ValueRange response=sheetServicio.spreadsheets().values()
                    .get(Google_Sheet_Id, Rango)
                    .execute();
                 System.out.println(""+Rango);
            List<List<Object>> values=response.getValues();

            if (values==null|| values.isEmpty()) {
                pbBusqueda.setVisible(false);
                System.out.println("No hay datos");
            }else{
                int index=1;
                Boolean valorEncotrado=false;
                for(List fila:values){
                    index++;
                    if(fila.get(5).toString().equals(txtBusqueda.getText())){
                       valorEncotrado=true;
                        actualizarCelda(""+celda+index, valor);
                        //actualizarCelda("BY"+index, txtHorafinalizada.getText());
                        //actualizarCelda("BZ"+index, txtRegistroLLegada.getText()); 
                    }
                    pbBusqueda.setVisible(false);
                    txtLogObservacion.setText("Registro Actualizado");
                    
                   
                }
                if(!valorEncotrado){
                    pbBusqueda.setVisible(false);
                    txtLogObservacion.setText("El DNI no existe, no se pudo actualizar");
                }
           
               
          
            }
        } catch (Exception e) {
            pbBusqueda.setVisible(false);
            e.printStackTrace();
            txtLogObservacion.setText(""+e);
           }   
        }
        
    }
    private static void actualizarCelda(String celda, String valor) {
         try{
             List<List<Object>> newValues = new ArrayList<>();
            List<Object> row = new ArrayList<>();
            row.add(valor);
            newValues.add(row);

            ValueRange body = new ValueRange().setValues(newValues);
             System.out.println(""+celda);
            sheetServicio.spreadsheets().values()
                    .update(Google_Sheet_Id,hojaID+"!"+celda, body)
                    .setValueInputOption("USER_ENTERED")
                    .execute();
         }catch(Exception e){
            System.out.println(""+e);
             e.printStackTrace();
         }
        
    }

    

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnFinalizada;
    private javax.swing.JButton btnLlegada;
    private javax.swing.JButton btnMotivoCreacion;
    private javax.swing.JButton btnPartener;
    private javax.swing.JButton btnRegistrollegada;
    private javax.swing.JButton btnSolucion;
    private javax.swing.JButton btnTicket;
    private javax.swing.JButton btnTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pbBusqueda;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCp;
    private javax.swing.JTextField txtCtoNap;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtHorafinalizada;
    private javax.swing.JTextField txtHorallegada;
    private javax.swing.JTextArea txtLogObservacion;
    private javax.swing.JTextField txtMac;
    private javax.swing.JTextField txtMotivoCreacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOt;
    private javax.swing.JTextField txtPartener;
    private javax.swing.JTextField txtPiso;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextField txtRegistroLLegada;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTicket;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTipoSolucion;
    // End of variables declaration//GEN-END:variables
}
